[package]
name = "workbench-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "pw"
path = "src/main.rs"

[dependencies]
workbench-core = { path = "../core" }
serde_json = "1.0.151"

[dev-dependencies]
serde = { version = "1.0.229", features = ["derive"] }
