//! The nine base texts of the study, and the numbers the prototype produced
//! for them.
//!
//! These are the Q4-Q12 base versions as they stood in the React prototype the
//! workbench replaces. They are here so the port can be held to the prototype's
//! arithmetic rather than merely resembling it: a readability figure recorded
//! during the study and one shown by this tool have to be the same number, or
//! the study's record and the tool's output cannot be compared at all.
//!
//! The expected metrics were generated by running the prototype's own
//! `analyze` and `countSyl` over these strings. They are an oracle, not a
//! judgement about what the right reading level is.

#![allow(dead_code)]

use workbench_core::hash::{Sha256Hex, Timestamp};
use workbench_core::protocol::{Question, Settings};
use workbench_core::rubric::{ChipId, Percent, Scores};

/// One base question: its number, its title, and the text the study used.
pub struct Base {
    pub ordinal: usize,
    pub title: &'static str,
    pub text: &'static str,
    /// The prototype's rubric chips: label and points.
    pub chips: &'static [(&'static str, i32)],
    /// What the prototype's `analyze` returned for `text`.
    pub words: usize,
    pub sentences: usize,
    pub grade: f64,
    pub ease: f64,
}

pub const BANK: &[Base] = &[
    Base {
        ordinal: 4,
        title: "Sets, Functions & Counting",
        text: r#"Question 4 - The Dessert Menu.
Let the universe be tray positions U = {1,...,8}. Let A = {1,2,3,4} hold cakes and B = {3,4,5,6} hold chocolate items.
Part 1. Compute A union B, A intersect B, A minus B, the symmetric difference of A and B, and the complement of A.
Part 2. Compute |A x B| and the size of the power set of A. State what each quantity counts.
Part 3. Classify each mapping as injective, surjective, bijective, or none, with justification. f1 maps {1,2,3,4} to {a,b,c} with f1(1)=a, f1(2)=b, f1(3)=c, f1(4)=a. f2 maps {1,2,3} to {a,b,c,d} with f2(1)=b, f2(2)=d, f2(3)=a. f3 maps {1,2,3} to {a,b,c} with f3(1)=c, f3(2)=a, f3(3)=b.
Part 4. A sundae is any subset of the 8 available toppings. Exhibit a bijection between sundaes and binary strings of length 8, then use the Bijection Rule to count the sundaes.
Part 5. How many strings of length 5 over {a,b,c} contain at least one a? Count by complement.
Part 6. How many strings of length 5 over {a,b,c} start with a or end with b? Cite the counting principle used.
Part 7. If 25 desserts are placed into 7 display cases, what is the largest number of desserts some case is guaranteed to contain? State the principle and show the calculation."#,
        chips: &[
            ("Set operators (5 ops)", 4),
            ("|AxB| and |P(A)|", 2),
            ("Function classification x3", 4),
            ("Bijection stated", 2),
            ("Bijection Rule count (256)", 2),
            ("Complement count (211)", 2),
            ("Inclusion-Exclusion (135)", 2),
            ("Pigeonhole (ceil 25/7 = 4)", 2),
        ],
        words: 222,
        sentences: 25,
        grade: 3.9,
        ease: 83.0,
    },
    Base {
        ordinal: 5,
        title: "Probability at the Salad Bar",
        text: r#"Question 5 - Probability at the Salad Bar.
Items i0 through i9 are assigned to 10 slots arranged in three rows: top row O00 O01 O02 O03, middle row O10 O11 O12 O13, bottom row O21 O22. All 10! assignments are equally likely.
Part 1. What is the probability that i9 is placed in the top row?
Part 2. Using the Additivity Axiom, compute the probability that i9 is in the top row or the bottom row. Justify why the axiom applies.
Part 3. Using the Inclusion-Exclusion Theorem, compute the probability that i8 is in the top row or i9 is in the top row.
Part 4. Using the Complement Theorem, compute the probability that i0 is not in slot O00.
Part 5. Compute the conditional probability that i9 is in slot O00 given that i9 is in the top row.
Part 6. Are the events "i8 in the top row" and "i9 in the top row" independent? Support your answer with a calculation.
Part 7. Prep station A prepares 60 percent of items and mislabels 2 percent of them. Station B prepares 40 percent and mislabels 5 percent. A random item is mislabeled. Use Bayes' Rule to find the probability it came from station B."#,
        chips: &[
            ("P(top row) = 4/10", 2),
            ("Additivity -> 3/5", 2),
            ("Incl-Excl -> 2/3", 2),
            ("Complement -> 9/10", 2),
            ("Conditional -> 1/4", 2),
            ("Independence: not indep.", 2),
            ("Bayes setup P(E)=0.032", 2),
            ("Bayes value 5/8", 2),
        ],
        words: 205,
        sentences: 23,
        grade: 5.4,
        ease: 72.0,
    },
    Base {
        ordinal: 6,
        title: "Propositional Logic",
        text: r#"Question 6 - The Kitchen Sensor Network.
Let p mean "the oven is on", q mean "the door is open", r mean "the alarm sounds".
Part 1. Translate into a propositional expression: "If the oven is on and the door is open, then the alarm sounds."
Part 2. Translate into natural English: not r implies (not p or not q).
Part 3. Build the complete truth table for (p and q) implies r. Is it satisfiable, a tautology, or a contradiction? If satisfiable but not a tautology, show one satisfying row and one falsifying row.
Part 4. Simplify not(p and not q) or q to a minimal equivalent expression. Cite the numbered law from the law sheet for every step.
Part 5. Using a truth table, prove this argument is valid: premises p implies q, and not q; conclusion not p. State explicitly what property of the table establishes validity."#,
        chips: &[
            ("English -> proposition", 2),
            ("Proposition -> English", 2),
            ("Truth table (8 rows)", 2),
            ("Classification + witness rows", 2),
            ("Simplification, laws cited", 4),
            ("Validity truth table", 2),
            ("Validity criterion stated", 2),
        ],
        words: 149,
        sentences: 17,
        grade: 5.8,
        ease: 69.0,
    },
    Base {
        ordinal: 7,
        title: "Arithmetic Proofs & Modular",
        text: r#"Question 7 - Arithmetic Proof Techniques.
Use only these definitions: x is even iff x = 2q for an integer q; x is odd iff x = 2q + 1; d divides x iff x = dq; a is congruent to b mod n iff n divides (a - b).
Part 1. Direct proof: prove the sum of two even integers is even.
Part 2. Proof by cases: prove that for every integer n, n squared is congruent to 0 or 1 mod 4.
Part 3. Contrapositive: prove that if n squared is even then n is even. State the contrapositive explicitly first.
Part 4. Contradiction: prove the sum of a rational number and an irrational number is irrational. State the negated assumption explicitly.
Part 5. Prove: if a is congruent to b mod n and c is congruent to d mod n, then a + c is congruent to b + d mod n. Trace every step to the divisibility definition.
Part 6. Prove or disprove: for all integers a and b, if a squared is congruent to b squared mod 4, then a is congruent to b mod 4."#,
        chips: &[
            ("Direct: even + even", 2),
            ("Cases: exhaustive split", 2),
            ("Cases: both closed", 2),
            ("Contrapositive stated", 2),
            ("Contrapositive proven", 2),
            ("Contradiction assumption", 2),
            ("Contradiction derived", 2),
            ("Modular: unpack witnesses", 2),
            ("Modular: recombine", 2),
            ("Counterexample mod 4", 2),
        ],
        words: 183,
        sentences: 20,
        grade: 4.7,
        ease: 78.0,
    },
    Base {
        ordinal: 8,
        title: "Sequences & Recurrences",
        text: r#"Question 8 - Sequences and Recurrences.
Part 1. For the sequence 4, 7, 10, 13, 16, ... write (a) a recursive form with initial condition and (b) a closed form.
Part 2. For each recurrence, state whether it is linear and whether it is homogeneous, with one sentence each: (a) a(n) = 2a(n-1) + 3; (b) a(n) = a(n-1) * a(n-2); (c) a(n) = 5a(n-1) - 6a(n-2).
Part 3. The Squemp enumeration satisfies q(0) = 0 and q(n) = 2q(n-1) + 3. Prove by induction that q(n) = 3(2^n - 1) for all n >= 0.
Part 4. Solve a(n) = 3a(n-1) with a(0) = 2. Give the closed form and verify it against a(1) and a(2).
Part 5. Solve the linear homogeneous recurrence a(n) = 5a(n-1) - 6a(n-2) with a(0) = 1 and a(1) = 4. Find the characteristic roots, the general solution, and the constants."#,
        chips: &[
            ("Recursive form", 2),
            ("Closed form 3n+4", 2),
            ("LHRR identification x3", 4),
            ("Induction: base", 2),
            ("Induction: hypothesis", 2),
            ("Induction: step", 2),
            ("First-order 2*3^n", 2),
            ("Characteristic roots 2,3", 2),
            ("Constants c1=-1, c2=2", 2),
        ],
        words: 128,
        sentences: 17,
        grade: 3.6,
        ease: 83.0,
    },
    Base {
        ordinal: 9,
        title: "Cryptography",
        text: r#"Question 9 - Securing the Recipe Book.
Part 1. Use the Euclidean Algorithm to compute gcd(252, 198). Show every division step.
Part 2. Compute phi(15) by listing the coprime residues, and state the value of phi(p) for a prime p with one sentence of justification.
Part 3. Use Fermat's Little Theorem to compute 7^222 mod 11. Show the exponent reduction explicitly.
Part 4. A toy RSA system uses p = 3, q = 11, and e = 7. (a) Verify (N, e) is a valid public key: compute N and check the coprimality condition. (b) Encrypt the message m = 2. (c) Find the private exponent d and decrypt your ciphertext to recover m. (d) In one or two sentences, what computationally hard problem protects the private key?"#,
        chips: &[
            ("Euclid trace -> 18", 2),
            ("phi(15)=8; phi(p)=p-1", 2),
            ("FLT reduction", 2),
            ("FLT value 5", 2),
            ("RSA key validity", 2),
            ("Encrypt c=29", 2),
            ("Decrypt d=3 -> m=2", 2),
            ("Hardness: factoring", 2),
        ],
        words: 124,
        sentences: 15,
        grade: 5.7,
        ease: 69.0,
    },
    Base {
        ordinal: 10,
        title: "Asymptotics & Algorithms",
        text: r#"Question 10 - Analyzing the Salad-Bar Shift Algorithm.
Algorithm ShiftBar(S1): for each row r in S1 (rows have widths 4, 4, 2): let w = width(r); for j = 0 to w - 1: S2[r][(j + 1) mod w] = S1[r][j]. Return S2.
Part 1. Give the tightest simple Theta class for each: 5n^2 + 3n; n log n + 20n; 2^n + n^3; 100; n! + 2^n.
Part 2. Prove from the definition that 5n^2 + 3n = O(n^2): exhibit constants c and k and verify the inequality.
Part 3. Is 5n^2 + 3n also Omega(n^2)? Conclude whether it is Theta(n^2), citing the definitions.
Part 4. Let n be the total number of slots. State the time complexity of ShiftBar in Theta notation and justify by tracing the loop structure.
Part 5. State the space complexity of ShiftBar. Distinguish total space from auxiliary space (excluding the output S2)."#,
        chips: &[
            ("Theta classes x5", 4),
            ("O-proof constants c,k", 2),
            ("O-inequality verified", 2),
            ("Omega and Theta conclusion", 2),
            ("Time Theta(n)", 2),
            ("Loop trace", 2),
            ("Space: total vs auxiliary", 2),
        ],
        words: 145,
        sentences: 20,
        grade: 4.2,
        ease: 78.0,
    },
    Base {
        ordinal: 11,
        title: "Relations",
        text: r#"Question 11 - Relations on the Menu Codes.
Part 1. Let A = {1, 2, 3, 4, 6, 12} and define R by: a R b iff a divides b. Draw the digraph of R.
Part 2. Determine with justification whether R is reflexive, irreflexive, symmetric, anti-symmetric, asymmetric, and transitive.
Part 3. Is R a partial order? If so, draw its Hasse diagram.
Part 4. Using your Hasse diagram, identify all maximal and minimal elements, and find the least upper bound and greatest lower bound of the pair {4, 6}.
Part 5. Define T on B = {0, 1, ..., 8} by a T b iff a is congruent to b mod 3. Prove T is an equivalence relation and list its equivalence classes."#,
        chips: &[
            ("Digraph + loops", 2),
            ("Six properties", 4),
            ("Poset conclusion", 2),
            ("Hasse diagram", 2),
            ("Maximal / minimal", 2),
            ("lub=12, glb=2", 2),
            ("Equivalence R/S/T", 2),
            ("Classes x3", 2),
        ],
        words: 120,
        sentences: 15,
        grade: 4.9,
        ease: 74.0,
    },
    Base {
        ordinal: 12,
        title: "Graphs & Delivery Routes",
        text: r#"Question 12 - Delivery Routes.
Six locations V = {A, B, C, D, E, F} are connected by roads: AB, AC, BC, BD, CD, DE, DF, EF.
Part 1. Draw the undirected graph and give the degree of each vertex.
Part 2. Classify each sequence as a walk, trail, path, circuit, and/or cycle, listing all labels that apply with one sentence each: (a) A, B, C, A; (b) A, B, D, C, B; (c) A, C, D, E, F.
Part 3. Does this graph have an Euler circuit? An Euler trail? Justify using vertex degrees, and exhibit an Euler trail if one exists.
Part 4. Exhibit a Hamilton path, and prove the graph has no Hamilton cycle.
Part 5. Draw a spanning tree and state how many edges any spanning tree of this graph must have.
Part 6. Starting from A and visiting neighbors in alphabetical order, give the visitation order for (a) Breadth-First Search and (b) Depth-First Search.
Part 7. Weight the roads: AB=4, AC=2, BC=1, BD=5, CD=8, DE=3, DF=6, EF=2. Find a minimum spanning tree with Kruskal's or Prim's algorithm, showing the order edges are considered, and give the total weight.
Part 8. Using those weights, run Dijkstra's algorithm from A. Give the final shortest distance to every vertex and show the distance-update table."#,
        chips: &[
            ("Drawing + degrees", 2),
            ("Walk taxonomy x3", 4),
            ("Euler criterion", 2),
            ("Euler trail shown", 2),
            ("Hamilton path", 2),
            ("No Hamilton cycle", 2),
            ("Spanning tree", 2),
            ("BFS trace", 2),
            ("DFS trace", 2),
            ("MST trace", 2),
            ("MST weight = 13", 2),
            ("Dijkstra distances", 2),
            ("Dijkstra table", 2),
        ],
        words: 222,
        sentences: 24,
        grade: 4.2,
        ease: 81.0,
    },
];

/// Look one up by its number on the assignment.
pub fn base(ordinal: usize) -> &'static Base {
    BANK.iter().find(|b| b.ordinal == ordinal).expect("no such question in the bank")
}

// ------------------------------------------------------------------ helpers

/// A digest that is a digest, for tests that do not care which one.
pub fn digest(seed: &str) -> Sha256Hex {
    Sha256Hex::of(seed.as_bytes())
}

/// `2026-08-27T09:00:00Z` plus `minutes`, so a test can order its own events
/// without a clock.
pub fn at(minutes: u32) -> Timestamp {
    let h = 9 + minutes / 60;
    let m = minutes % 60;
    Timestamp::parse(&format!("2026-08-27T{:02}:{:02}:00Z", h, m)).expect("well-formed instant")
}

pub fn pct(v: f64) -> Percent {
    Percent::new(v).expect("a percentage")
}

/// A question built from the bank, with its prototype rubric loaded in.
pub fn question(ordinal: usize) -> Question {
    let b = base(ordinal);
    let mut q = Question::new(b.ordinal, b.title, b.text).expect("bank text is not empty");
    for (label, points) in b.chips {
        q.rubric_mut().add_chip(label, *points).expect("bank chip is valid");
    }
    q
}

/// A small question with two chips worth 2 and 8, so a grade lands on a round
/// number and a reader can check the arithmetic by eye.
pub fn simple() -> Question {
    let mut q = Question::new(1, "Simple", "Prove that two plus two is four.").unwrap();
    q.rubric_mut().add_chip("States the claim", 2).unwrap();
    q.rubric_mut().add_chip("Proves the claim", 8).unwrap();
    q
}

/// Mark every chip of a question's current rubric revision at `each`.
pub fn mark_all(q: &Question, each: f64) -> Scores {
    q.rubric()
        .current()
        .chips
        .iter()
        .map(|c| (c.id.clone(), pct(each)))
        .collect()
}

/// Mark named chips at one level and everything else at zero.
pub fn mark_only(q: &Question, full: &[&str], each: f64) -> Scores {
    q.rubric()
        .current()
        .chips
        .iter()
        .map(|c| {
            let v = if full.contains(&c.id.as_str()) { each } else { 0.0 };
            (c.id.clone(), pct(v))
        })
        .collect()
}

pub fn chip(q: &Question, n: usize) -> ChipId {
    q.rubric().current().chips[n].id.clone()
}

pub fn settings(threshold: f64) -> Settings {
    Settings { threshold: pct(threshold), ..Settings::default() }
}
